/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomChartsPanel: typeof import('./components/panels/BottomChartsPanel.vue')['default']
    ChartWidget: typeof import('./components/widgets/ChartWidget.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Front_page: typeof import('./components/front_page.vue')['default']
    IndicatorRadar: typeof import('./components/charts/IndicatorRadar.vue')['default']
    KPIDashboard: typeof import('./components/charts/KPIDashboard.vue')['default']
    LandTransferSankey: typeof import('./components/charts/LandTransferSankey.vue')['default']
    LandUseBarChart: typeof import('./components/charts/LandUseBarChart.vue')['default']
    LandUsePieChart: typeof import('./components/charts/LandUsePieChart.vue')['default']
    LandUseTrendChart: typeof import('./components/charts/LandUseTrendChart.vue')['default']
    LeftStatsPanel: typeof import('./components/panels/LeftStatsPanel.vue')['default']
    Login_page: typeof import('./components/login_page.vue')['default']
    PlaceholderChart: typeof import('./components/charts/PlaceholderChart.vue')['default']
    PolygonAair: typeof import('./components/PolygonAair.vue')['default']
    RoseCurrent: typeof import('./components/charts/RoseCurrent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackedAreaChart: typeof import('./components/charts/StackedAreaChart.vue')['default']
    StackedTrend: typeof import('./components/charts/StackedTrend.vue')['default']
    StatItem: typeof import('./components/panels/StatItem.vue')['default']
    StatsCard: typeof import('./components/panels/StatsCard.vue')['default']
    TimeController: typeof import('./components/controls/TimeController.vue')['default']
    YearRangeSelector: typeof import('./components/controls/YearRangeSelector.vue')['default']
  }
}
